# Generated by Django 3.2.7 on 2021-09-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkgif', '0002_animation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animation',
            name='user',
        ),
    ]
